name: Experiment 01 - Nil Optimization

on:
  push:
    branches:
      - copilot/**
  workflow_dispatch:

jobs:
  nil-optimization-experiment:
    name: Measure Nil Optimization Impact
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Need full history to checkout master branch
    
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'
    
    - name: Install reproducible build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y strip-nondeterminism
    
    - name: Run Nil Optimization Experiment
      run: |
        cd nil-optimization/experiments/uberjar-comparison
        bash 01-nil-optimization.sh
    
    - name: Upload experiment results
      uses: actions/upload-artifact@v4
      with:
        name: nil-optimization-results
        path: nil-optimization/experiments/uberjar-comparison/results/01-nil-optimization/
        retention-days: 90
    
    - name: Display Results Summary
      if: always()
      run: |
        RESULTS_DIR="nil-optimization/experiments/uberjar-comparison/results/01-nil-optimization"
        if [ -f "$RESULTS_DIR/summary.txt" ]; then
          echo "### Experiment Results" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          cat "$RESULTS_DIR/summary.txt" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi
    
    - name: Verify Results Match Expected
      if: github.event_name == 'push'
      run: |
        RESULTS_DIR="nil-optimization/experiments/uberjar-comparison/results/01-nil-optimization"
        
        # Verify experiment completed successfully
        if [ ! -f "$RESULTS_DIR/summary.txt" ]; then
          echo "ERROR: Experiment did not generate expected results"
          exit 1
        fi
        
        # Check that both JARs were analyzed
        if [ ! -f "$RESULTS_DIR/baseline.jar" ]; then
          echo "ERROR: Baseline JAR not found"
          exit 1
        fi
        
        if [ ! -f "$RESULTS_DIR/optimized.jar" ]; then
          echo "ERROR: Optimized JAR not found"
          exit 1
        fi
        
        # Check for class differences report
        if [ ! -f "$RESULTS_DIR/class-differences.txt" ]; then
          echo "WARNING: Class differences report not found"
        fi
        
        echo "✓ Experiment completed successfully"
        echo "✓ All expected artifacts generated"
